name: "Terraform_Apply"
on:
 push: 
  branches:
       - main
env:
 OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
 OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
 OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
 OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
 OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
 OCI_CLI_KEYPATH: ${{ secrets.OCI_CLI_KEYPATH }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Terraform 
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run:  terraform init --upgrade

      - name: Terraform Plan
        run:  terraform plan

      - name: Terraform Apply
        run:  terraform apply -auto-approve

#      - name: Terraform Plan Destroy
#        run:  terraform plan -destroy

      - name: Terraform Show
        run:  terraform show
        
      - name: Terraform Destroy
        run:  terraform destroy -auto-approve