name: "Terraform_Init"
on:
 push: 
  branches:
       - main
       
jobs:
  terraform:
    runs-on: ubuntu-latest
   
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      OCI_INSTANCE_ID: ${{ secrets.OCI_INSTANCE_ID }}
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Terraform 
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init --upgrade